import type { HistoricalExplorerDataset } from './types';

export const genesisDemoData: HistoricalExplorerDataset = {
  id: 'genesis-history',
  title: 'Genesi · storia intorno al testo',
  subtitle: 'Popoli, poteri, luoghi, memorie e processi storici messi in relazione con Genesi senza confondere racconto e ricostruzione storica.',
  defaultRange: [-1000, -400],
  entities: [
    {
      id: 'neo-assyria',
      type: 'empire',
      label: 'Impero neo-assiro',
      summary: 'Grande potenza del Vicino Oriente del I millennio a.C.; costituisce uno degli sfondi imperiali entro cui maturano memorie e tradizioni bibliche.',
      temporal: { start: -911, end: -609, precision: 'range' },
      spatial: { lat: 36.35, lng: 43.15, region: 'Mesopotamia e Levante' },
      epistemicStatus: 'attested',
      relations: [
        { targetId: 'nineveh', kind: 'context', label: 'Ninive come capitale dell’ultima fase imperiale' },
      ],
      sources: [{ label: 'Cronologia storica del Vicino Oriente antico' }],
    },
    {
      id: 'neo-babylon',
      type: 'empire',
      label: 'Impero neobabilonese',
      summary: 'La conquista di Gerusalemme e l’esilio babilonese costituiscono un contesto decisivo per la rielaborazione dell’identità e delle tradizioni di Israele.',
      temporal: { start: -626, end: -539, precision: 'range' },
      spatial: { lat: 32.54, lng: 44.42, region: 'Mesopotamia e Levante' },
      epistemicStatus: 'attested',
      biblicalRefs: ['2Re 24–25'],
      relations: [
        { targetId: 'babylon', kind: 'context', label: 'Babilonia come centro politico imperiale' },
        { targetId: 'genesis-formation', kind: 'composition', label: 'Contesto rilevante per fasi di rielaborazione delle tradizioni' },
      ],
      sources: [{ label: 'Storia neo-babilonese' }],
    },
    {
      id: 'achaemenid-persia',
      type: 'empire',
      label: 'Impero persiano achemenide',
      summary: 'Dopo il 539 a.C. il Levante entra nell’orizzonte imperiale persiano; Yehud e la ricostruzione comunitaria formano un contesto importante per la storia del Pentateuco.',
      temporal: { start: -539, end: -332, precision: 'range' },
      spatial: { lat: 32.19, lng: 48.26, region: 'Vicino Oriente' },
      epistemicStatus: 'attested',
      biblicalRefs: ['Esd 1'],
      relations: [
        { targetId: 'susa', kind: 'context', label: 'Susa come uno dei principali centri achemenidi' },
        { targetId: 'jerusalem', kind: 'context', label: 'Yehud e Gerusalemme nel quadro imperiale persiano' },
        { targetId: 'genesis-formation', kind: 'composition', label: 'Contesto spesso collegato a fasi dell’assetto pentateucale' },
      ],
      sources: [{ label: 'Storia achemenide e Yehud persiana' }],
    },
    {
      id: 'nineveh',
      type: 'city',
      label: 'Ninive',
      summary: 'Grande centro urbano dell’Assiria e capitale imperiale sotto gli ultimi sovrani neo-assiri.',
      temporal: { start: -705, end: -612, precision: 'range' },
      spatial: { lat: 36.36, lng: 43.15, region: 'Alta Mesopotamia' },
      epistemicStatus: 'attested',
      relations: [{ targetId: 'neo-assyria', kind: 'context', label: 'Capitale neo-assira' }],
      sources: [{ label: 'Archeologia e storia neo-assira' }],
    },
    {
      id: 'babylon',
      type: 'city',
      label: 'Babilonia',
      summary: 'Centro urbano della Mesopotamia meridionale e capitale dell’impero neobabilonese nel VI secolo a.C.',
      temporal: { start: -626, end: -539, precision: 'range' },
      spatial: { lat: 32.54, lng: 44.42, region: 'Babilonia' },
      epistemicStatus: 'attested',
      biblicalRefs: ['2Re 24–25'],
      relations: [{ targetId: 'neo-babylon', kind: 'context', label: 'Capitale neobabilonese' }],
      sources: [{ label: 'Archeologia e storia di Babilonia' }],
    },
    {
      id: 'susa',
      type: 'city',
      label: 'Susa',
      summary: 'Antica città dell’Elam e importante residenza reale nel sistema politico achemenide.',
      temporal: { start: -550, end: -330, precision: 'range' },
      spatial: { lat: 32.19, lng: 48.26, region: 'Susiana / Elam' },
      epistemicStatus: 'attested',
      relations: [{ targetId: 'achaemenid-persia', kind: 'context', label: 'Centro achemenide' }],
      sources: [{ label: 'Archeologia e storia achemenide' }],
    },
    {
      id: 'jerusalem',
      type: 'city',
      label: 'Gerusalemme',
      summary: 'Centro politico e cultuale di Giuda; dopo il 539 a.C. diventa il fulcro della provincia persiana di Yehud e della ricostruzione comunitaria.',
      temporal: { start: -1000, end: -400, precision: 'range' },
      spatial: { lat: 31.78, lng: 35.22, region: 'Giuda / Yehud' },
      epistemicStatus: 'attested',
      biblicalRefs: ['2Re 24–25', 'Esd 1'],
      relations: [
        { targetId: 'neo-babylon', kind: 'interaction', label: 'Conquista babilonese e distruzione del 586 a.C.' },
        { targetId: 'achaemenid-persia', kind: 'context', label: 'Ricostruzione in età persiana' },
      ],
      sources: [{ label: 'Archeologia e storia di Gerusalemme e Yehud' }],
    },
    {
      id: 'memphis',
      type: 'city',
      label: 'Menfi',
      summary: 'Grande centro dell’Egitto antico e utile ancoraggio geografico per il contesto egiziano evocato dalle tradizioni bibliche.',
      temporal: { start: -1000, end: -400, precision: 'range' },
      spatial: { lat: 29.85, lng: 31.25, region: 'Basso Egitto' },
      epistemicStatus: 'attested',
      relations: [{ targetId: 'egypt', kind: 'context', label: 'Centro storico dell’Egitto' }],
      sources: [{ label: 'Storia e archeologia dell’Egitto antico' }],
    },
    {
      id: 'genesis-formation',
      type: 'redaction',
      label: 'Formazione di Genesi',
      summary: 'Processo plurale di tradizione, raccolta, riscrittura e redazione. Le datazioni precise dipendono dal modello critico adottato.',
      temporal: { start: -800, end: -400, precision: 'range' },
      spatial: { lat: 31.78, lng: 35.22, region: 'Israele / Giuda / diaspora' },
      epistemicStatus: 'debated',
      biblicalRefs: ['Genesi'],
      relations: [
        { targetId: 'neo-babylon', kind: 'context', label: 'Fase esilica' },
        { targetId: 'achaemenid-persia', kind: 'context', label: 'Fase persiana' },
      ],
      sources: [{ label: 'Modelli storico-critici della formazione del Pentateuco', note: 'Cronologia e stratificazione restano discusse.' }],
    },
    {
      id: 'flood-traditions',
      type: 'event',
      label: 'Tradizioni di grandi inondazioni',
      summary: 'Tradizioni mesopotamiche di grandi inondazioni costituiscono un comparandum culturale per Gen 6–9; non sono una prova della storicità del racconto così come narrato.',
      temporal: { precision: 'unknown' },
      spatial: { lat: 32.5, lng: 44.4, region: 'Mesopotamia' },
      epistemicStatus: 'comparandum',
      biblicalRefs: ['Gen 6–9'],
      relations: [{ targetId: 'mesopotamia', kind: 'memory', label: 'Comparazione culturale' }],
      sources: [{ label: 'Tradizioni mesopotamiche del diluvio' }],
    },
    {
      id: 'mesopotamia',
      type: 'region',
      label: 'Mesopotamia',
      summary: 'Area culturale fondamentale per il confronto con cosmogonie, genealogie, tradizioni di diluvio e culture urbane presenti nell’orizzonte comparativo di Genesi.',
      temporal: { precision: 'unknown' },
      spatial: { lat: 33.3, lng: 44.4, region: 'Mesopotamia' },
      epistemicStatus: 'attested',
      biblicalRefs: ['Gen 1–11'],
      relations: [],
      sources: [{ label: 'Vicino Oriente antico' }],
    },
    {
      id: 'canaan',
      type: 'region',
      label: 'Canaan / Levante',
      summary: 'Spazio geografico e culturale delle tradizioni patriarcali e delle successive memorie di Israele.',
      temporal: { precision: 'unknown' },
      spatial: { lat: 31.8, lng: 35.2, region: 'Levante' },
      epistemicStatus: 'attested',
      biblicalRefs: ['Gen 12–36'],
      relations: [],
      sources: [{ label: 'Archeologia e storia del Levante' }],
    },
    {
      id: 'egypt',
      type: 'region',
      label: 'Egitto',
      summary: 'Potenza regionale e spazio narrativo decisivo nel ciclo di Giuseppe. La relazione tra dettagli narrativi e specifiche fasi storiche va valutata caso per caso.',
      temporal: { precision: 'unknown' },
      spatial: { lat: 30.04, lng: 31.24, region: 'Egitto' },
      epistemicStatus: 'attested',
      biblicalRefs: ['Gen 37–50'],
      relations: [{ targetId: 'memphis', kind: 'context', label: 'Menfi come ancoraggio storico-geografico' }],
      sources: [{ label: 'Storia dell’Egitto e relazioni con il Levante' }],
    },
  ],
};
