'use client';

import Link from 'next/link';
import { useMemo, useState } from 'react';
import { categoryLabel } from '../lib/bibleRouting';
import { studyContextHref } from '../study-context/context';

type Source={_id:string;sigla?:string;nome?:string;descrizione?:any;tipo?:any;periodo?:any;datazione?:any;note?:any};
type Usage={_id:string;numero:number;titolo?:string;libro?:{_id:string;titolo:string;categoriaId?:string};sourceIds:string[]};
const text=(v:any):string=>{if(v==null)return '';if(typeof v==='string'||typeof v==='number')return String(v);if(Array.isArray(v))return v.map(text).filter(Boolean).join(' · ');return v.etichetta||v.descrizione||v.nota||v.nome||v.titolo||''};
const slug=(id:string)=>id.replace(/^libro-/,'');

export default function SourcesModelsMap({sources,usages}:{sources:Source[];usages:Usage[]}){
 const [query,setQuery]=useState(''); const [selected,setSelected]=useState<string|null>(null); const [category,setCategory]=useState('tutti');
 const categories=useMemo(()=>Array.from(new Set(usages.map(u=>u.libro?.categoriaId).filter(Boolean) as string[])),[usages]);
 const stats=useMemo(()=>new Map(sources.map(s=>{const hits=usages.filter(u=>u.sourceIds.includes(s._id));const books=new Map(hits.filter(h=>h.libro).map(h=>[h.libro!._id,h.libro!]));return [s._id,{hits,books:Array.from(books.values())}]})),[sources,usages]);
 const filtered=useMemo(()=>sources.filter(s=>{const stat=stats.get(s._id);const q=query.toLowerCase();const matchesText=!q||[s.sigla,s.nome,text(s.descrizione),text(s.tipo)].some(v=>(v||'').toLowerCase().includes(q));const matchesCat=category==='tutti'||stat?.hits.some(h=>h.libro?.categoriaId===category);return matchesText&&matchesCat}),[sources,query,category,stats]);
 const active=selected?filtered.find(s=>s._id===selected)||sources.find(s=>s._id===selected):null;
 const activeStat=active?stats.get(active._id):null;
 const contextualHref=(bookId:string, chapter?:number)=>{
   const bookSlug=slug(bookId);
   const base=chapter?`/bibbia/${bookSlug}/${chapter}`:`/bibbia/${bookSlug}`;
   const href=studyContextHref(base,{book:bookSlug,chapter,source:'source',entity:active?._id});
   return chapter?`${href}#livelli-critici`:href;
 };
 return <div className="grid gap-8 lg:grid-cols-[360px_minmax(0,1fr)]">
  <aside className="h-fit lg:sticky lg:top-36"><div className="rounded-2xl border border-papyrus-line bg-paper-card p-4"><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Cerca sigla o modello…" aria-label="Cerca fonte o modello" className="min-h-11 w-full rounded-full border border-papyrus-line bg-papyrus px-4 text-sm outline-none focus:border-bronze"/><div className="mt-3 flex flex-wrap gap-2"><button onClick={()=>setCategory('tutti')} className={`rounded-full px-3 py-1.5 text-xs ${category==='tutti'?'bg-ink text-papyrus':'border border-papyrus-line text-ink-soft'}`}>Tutti</button>{categories.map(c=><button key={c} onClick={()=>setCategory(c)} className={`rounded-full px-3 py-1.5 text-xs ${category===c?'bg-ink text-papyrus':'border border-papyrus-line text-ink-soft'}`}>{categoryLabel(c)}</button>)}</div></div><div className="mt-4 max-h-[65vh] space-y-2 overflow-auto pr-1">{filtered.map(s=>{const st=stats.get(s._id);return <button key={s._id} onClick={()=>setSelected(s._id)} className={`w-full rounded-xl border p-4 text-left transition ${selected===s._id?'border-bronze bg-paper-card':'border-papyrus-line bg-paper-card/45 hover:border-bronze'}`}><div className="flex items-center justify-between gap-3"><strong className="font-mono text-sm text-bronze">{s.sigla||'—'}</strong><span className="text-[10px] text-ink-faint">{st?.hits.length||0} cap.</span></div><p className="mt-2 font-serif text-lg font-bold">{s.nome||s._id}</p><p className="mt-1 text-xs text-ink-faint">{st?.books.length||0} libri</p></button>})}</div></aside>
  <section>{active&&activeStat?<><div className="rounded-2xl border border-papyrus-line bg-paper-card p-6 md:p-8"><div className="flex flex-wrap items-start justify-between gap-5"><div><p className="font-mono text-sm font-bold text-bronze">{active.sigla||'—'}</p><h2 className="mt-2 font-serif text-4xl font-bold">{active.nome||active._id}</h2></div>{text(active.tipo)&&<span className="rounded-full border border-papyrus-line px-3 py-1 text-xs uppercase tracking-wider text-ink-faint">{text(active.tipo)}</span>}</div>{text(active.descrizione)&&<p className="reading-text mt-6 text-ink-soft">{text(active.descrizione)}</p>}<div className="mt-6 grid gap-4 sm:grid-cols-3"><div className="rounded-xl border border-papyrus-line p-4"><span className="text-xs text-ink-faint">Libri</span><strong className="mt-1 block font-serif text-3xl">{activeStat.books.length}</strong></div><div className="rounded-xl border border-papyrus-line p-4"><span className="text-xs text-ink-faint">Capitoli</span><strong className="mt-1 block font-serif text-3xl">{activeStat.hits.length}</strong></div><div className="rounded-xl border border-papyrus-line p-4"><span className="text-xs text-ink-faint">Periodo / nota</span><p className="mt-1 text-sm leading-5 text-ink-soft">{text(active.periodo)||text(active.datazione)||text(active.note)||'Non specificato'}</p></div></div></div>
   <div className="mt-6"><p className="font-mono text-[10px] uppercase tracking-widest text-bronze">Mappa nel corpus</p><h3 className="mt-2 font-serif text-3xl font-bold">Libri e capitoli collegati</h3><p className="mt-2 max-w-2xl text-sm leading-6 text-ink-faint">Entrando nel corpus da una fonte, Biblia Fontes conserva questa origine nel contesto di studio e porta l’utente verso l’apparato critico pertinente.</p><div className="mt-5 space-y-4">{activeStat.books.map(book=>{const chapters=activeStat.hits.filter(h=>h.libro?._id===book._id).sort((a,b)=>a.numero-b.numero);return <article key={book._id} className="rounded-2xl border border-papyrus-line bg-paper-card/55 p-5"><div className="flex flex-wrap items-center justify-between gap-4"><div><p className="text-xs text-ink-faint">{categoryLabel(book.categoriaId)}</p><Link href={contextualHref(book._id)} className="font-serif text-2xl font-bold hover:text-bronze">{book.titolo}</Link></div><span className="text-sm text-ink-faint">{chapters.length} capitoli</span></div><div className="mt-4 flex flex-wrap gap-2">{chapters.map(ch=><Link key={ch._id} href={contextualHref(book._id,ch.numero)} title={ch.titolo||`Capitolo ${ch.numero}`} className="rounded-full border border-papyrus-line px-3 py-1.5 text-sm text-ink-soft hover:border-bronze hover:text-bronze">{ch.numero}</Link>)}</div></article>})}{!activeStat.books.length&&<p className="rounded-xl border border-dashed border-papyrus-line p-6 text-ink-faint">Nessuna attribuzione di capitolo collegata a questo documento fonteBiblica.</p>}</div></div></>:<div className="rounded-2xl border border-dashed border-papyrus-line p-8 md:p-12"><p className="font-mono text-[10px] uppercase tracking-widest text-bronze">Esplora</p><h2 className="mt-3 font-serif text-4xl font-bold">Seleziona una fonte o un modello</h2><p className="mt-4 max-w-xl leading-7 text-ink-soft">La mappa mostrerà i libri e i capitoli nei quali il documento è realmente referenziato da Sanity. Nessuna relazione viene inferita dalla sola sigla.</p></div>}</section>
 </div>
}
