'use client';

import Link from 'next/link';
import { useMemo, useState } from 'react';
import type { HistoryIndexView } from '../data-access/history';
import GlobalHistoricalMap from './GlobalHistoricalMap';

type Mode = 'book'|'date'|'map';
const categoryOrder=['Pentateuco','Libri storici','Sapienziali e poetici','Profeti','Vangeli','Atti degli Apostoli','Lettere Paoline','Ebrei','Lettere Cattoliche','Apocalisse'];
const presets=[-1200,-1000,-722,-586,-539,-332,-167,-63,30,70,100];
const typeLabels:Record<string,string>={event:'evento',people:'popolo',empire:'impero',city:'città',region:'regione',person:'persona',institution:'istituzione',practice:'pratica',text:'testo',redaction:'redazione',witness:'testimone'};
const statusLabels:Record<string,string>={attested:'attestato',probable:'probabile',debated:'discusso',memory:'memoria',comparandum:'comparandum',narrative:'narrativo',undatable:'non databile'};
function formatYear(y:number){return y<0?`${Math.abs(y)} a.C.`:y===0?'0':`${y} d.C.`}
function activeAt(e:{start?:number;end?:number},y:number){return e.start!==undefined&&e.start<=y&&(e.end??e.start)>=y}

export default function HistoryHubSurface({history,basePath='/historical-explorer',corpusPath='/'}:{history:HistoryIndexView;basePath?:string;corpusPath?:string}){
 const [mode,setMode]=useState<Mode>('map');
 const initial=history.range[0]<=-586&&history.range[1]>=-586?-586:Math.round((history.range[0]+history.range[1])/2);
 const [year,setYear]=useState(initial);
 const grouped=useMemo(()=>{const m=new Map<string,typeof history.datasets>();for(const f of history.datasets){const k=f.category||'Altri libri';m.set(k,[...(m.get(k)||[]),f])}return [...m.entries()].sort((a,b)=>{const ai=categoryOrder.indexOf(a[0]),bi=categoryOrder.indexOf(b[0]);return (ai<0?99:ai)-(bi<0?99:bi)})},[history.datasets]);
 const dated=useMemo(()=>history.datasets.flatMap(f=>{const active=f.entities.filter(e=>activeAt(e,year));return active.length?[{...f,activeEntities:active}]:[]}),[history.datasets,year]);

 return <main className="mx-auto max-w-[1320px] px-5 py-10 md:px-8 md:py-14">
  <header className="grid gap-8 border-b border-papyrus-line pb-9 lg:grid-cols-[minmax(0,1fr)_330px] lg:items-end"><div><p className="font-mono text-[9px] uppercase tracking-[0.2em] text-bronze">Esploratore storico</p><h1 className="mt-2 font-serif text-5xl font-semibold md:text-6xl">Testo, tempo e spazio.</h1><p className="reading-text mt-5 max-w-[72ch] text-ink-soft">Entra da un libro, attraversa il corpus per data oppure osserva sulla mappa come luoghi, poteri, eventi e tradizioni cambiano nel tempo.</p></div><p className="border-l border-papyrus-line pl-6 text-xs leading-6 text-ink-faint">Le relazioni conservano il loro grado di affidabilità. La carta non trasforma la narrazione biblica in cronaca: mostra le coordinate storiche associate ai dati disponibili.</p></header>
  <nav className="mt-6 flex gap-6 border-b border-papyrus-line" aria-label="Modalità di esplorazione storica">{([['book','Per libro'],['date','Per data'],['map','Mappa']] as const).map(([id,label])=><button key={id} type="button" onClick={()=>setMode(id)} className={`border-b-2 pb-3 text-sm font-semibold ${mode===id?'border-bronze text-ink':'border-transparent text-ink-faint hover:text-ink'}`}>{label}</button>)}</nav>

  {mode==='book'&&<div className="mt-9 grid gap-9 lg:grid-cols-[190px_minmax(0,1fr)] lg:gap-10"><aside><p className="font-mono text-[9px] uppercase tracking-[0.16em] text-ink-faint">Ordine canonico</p><h2 className="mt-2 font-serif text-2xl font-semibold">Scegli un libro</h2><p className="mt-2 text-xs leading-5 text-ink-faint">Il libro resta il punto di partenza più naturale per chi arriva dal testo biblico.</p><p className="mt-4 border-l border-papyrus-line pl-3 text-[10px] leading-5 text-ink-faint">L’orizzonte storico indica il periodo coperto dalle relazioni del libro, non la sua data di composizione.</p><Link href={corpusPath} className="mt-6 inline-flex text-xs text-ink-soft hover:text-ink">← Corpus biblico</Link></aside><div className="border-t border-papyrus-line">{grouped.map(([cat,fields])=><section key={cat} className="grid gap-5 border-b border-papyrus-line py-6 md:grid-cols-[160px_minmax(0,1fr)]"><h2 className="font-serif text-lg font-semibold">{cat}</h2><div className="grid gap-x-6 sm:grid-cols-2 xl:grid-cols-3">{fields.map(f=><Link key={f.id} href={`${basePath}/${f.slug}`} className="group block border-b border-papyrus-line/70 py-3 hover:border-bronze/50"><span className="font-serif text-[1.05rem] font-semibold text-ink-soft group-hover:text-ink">{f.title}</span>{(f.start!==undefined||f.end!==undefined)&&<span className="mt-1 block font-mono text-[9px] text-ink-faint">ORIZZONTE STORICO · {f.start!==undefined?formatYear(f.start):'…'} — {f.end!==undefined?formatYear(f.end):'…'}</span>}</Link>)}</div></section>)}</div></div>}

  {mode==='date'&&<section className="mt-9"><div className="grid gap-8 border-b border-papyrus-line pb-8 lg:grid-cols-[210px_minmax(0,1fr)] lg:gap-12"><header><p className="font-mono text-[9px] uppercase tracking-[0.16em] text-bronze">Anno</p><h2 className="mt-2 font-serif text-4xl font-semibold">{formatYear(year)}</h2><p className="mt-3 text-xs leading-5 text-ink-faint">Mostra le relazioni i cui intervalli comprendono l’anno scelto.</p></header><div><div className="mb-2 flex justify-between text-[10px] text-ink-faint"><span>{formatYear(history.range[0])}</span><span>{formatYear(history.range[1])}</span></div><input type="range" min={history.range[0]} max={history.range[1]} value={year} onChange={e=>setYear(Number(e.target.value))} className="w-full accent-current" aria-label="Anno storico"/><div className="mt-4 flex flex-wrap gap-2">{presets.filter(p=>p>=history.range[0]&&p<=history.range[1]).map(p=><button key={p} onClick={()=>setYear(p)} className={`border px-2.5 py-1 text-[10px] ${year===p?'border-ink bg-ink text-papyrus':'border-papyrus-line text-ink-faint hover:border-bronze'}`}>{formatYear(p)}</button>)}</div></div></div><div className="grid gap-9 py-9 lg:grid-cols-[210px_minmax(0,1fr)] lg:gap-12"><aside><p className="font-mono text-[9px] uppercase tracking-[0.16em] text-ink-faint">Nel corpus</p><p className="mt-2 font-serif text-4xl font-semibold">{dated.length}</p><p className="text-xs text-ink-faint">libri coinvolti</p></aside><div className="border-t border-papyrus-line">{dated.map(f=><article key={f.id} className="grid gap-5 border-b border-papyrus-line py-7 md:grid-cols-[180px_minmax(0,1fr)]"><header><p className="font-mono text-[9px] uppercase tracking-[0.14em] text-bronze">{f.category}</p><h3 className="mt-1 font-serif text-xl font-semibold">{f.title}</h3><Link href={`${basePath}/${f.slug}?year=${year}`} className="mt-3 inline-flex text-xs font-semibold text-bronze hover:text-ink">Apri il contesto →</Link></header><div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-3">{f.activeEntities.slice(0,9).map(e=><Link key={e.id} href={`${basePath}/${f.slug}?year=${year}&entity=${encodeURIComponent(e.id)}`} className="border-l border-papyrus-line pl-3 hover:border-bronze"><strong className="font-serif text-base font-semibold text-ink-soft">{e.label}</strong><span className="mt-1 block text-[10px] text-ink-faint">{typeLabels[e.type]||e.type} · {statusLabels[e.epistemicStatus]||e.epistemicStatus}</span></Link>)}</div></article>)}</div></div></section>}

  {mode==='map'&&<GlobalHistoricalMap history={history} basePath={basePath}/>} 
 </main>;
}
