'use client';

import { useEffect, useMemo, useRef, useState, type PointerEvent as ReactPointerEvent, type ReactNode } from 'react';
import { historicalMapPresets, inferHistoricalMapPreset, type HistoricalMapPresetId } from './mapPresets';

export type MapLayer = 'places' | 'powers' | 'events' | 'texts';
export type MapEpistemicStatus = 'attested' | 'probable' | 'debated' | 'memory' | 'comparandum' | 'narrative' | 'undatable';
export type HistoricalMapPoint = { id: string; label: string; type: string; lat: number; lng: number; active?: boolean; selected?: boolean; subtitle?: string; epistemicStatus?: MapEpistemicStatus };
export type HistoricalMapArea = { id: string; entityId: string; label: string; coordinates: number[][] };
type Props = { points: HistoricalMapPoint[]; areas?: HistoricalMapArea[]; selectedId?: string; onSelect?: (id: string) => void; preset?: HistoricalMapPresetId; heightClassName?: string; headerRight?: ReactNode; footer?: ReactNode; contextTitle?: string; contextSummary?: string; visibleLayers?: MapLayer[]; onVisibleLayersChange?: (layers: MapLayer[]) => void; visibleStatuses?: MapEpistemicStatus[]; onVisibleStatusesChange?: (statuses: MapEpistemicStatus[]) => void };
type Camera = { zoom: number; x: number; y: number };
type Projected = HistoricalMapPoint & { x: number; y: number };
type DisplayPoint = Projected & { dx: number; dy: number; groupSize: number };
type Cluster = { key: string; x: number; y: number; points: Projected[] };

const W = 1200, H = 680, MIN_ZOOM = 1, MAX_ZOOM = 4;
const ALL_LAYERS: MapLayer[] = ['places', 'powers', 'events', 'texts'];
const ALL_STATUSES: MapEpistemicStatus[] = ['attested', 'probable', 'debated', 'memory', 'comparandum', 'narrative', 'undatable'];
const baseAssets: Record<HistoricalMapPresetId, string> = { 'near-east': '/maps/historical-near-east.svg', levant: '/maps/historical-levant.svg', 'eastern-mediterranean': '/maps/historical-eastern-mediterranean.svg' };
const layerMeta: Record<MapLayer, { label: string; description: string; color: string; glyph: string }> = {
  places: { label: 'Luoghi', description: 'città e regioni', color: '#2f2924', glyph: '●' },
  powers: { label: 'Territori e poteri', description: 'regni, imperi e popoli', color: '#443222', glyph: '⬡' },
  events: { label: 'Eventi', description: 'eventi localizzati', color: '#7a3028', glyph: '◆' },
  texts: { label: 'Testi e tradizioni', description: 'formazione, redazione e trasmissione', color: '#9b6a38', glyph: '▣' },
};
const statusGroups: Array<{ label: string; statuses: MapEpistemicStatus[]; description: string }> = [
  { label: 'Attestato', statuses: ['attested'], description: 'bordo pieno' },
  { label: 'Probabile', statuses: ['probable'], description: 'bordo quasi pieno' },
  { label: 'Discusso', statuses: ['debated'], description: 'bordo tratteggiato' },
  { label: 'Memoria / comparandum', statuses: ['memory', 'comparandum'], description: 'tratteggio marcato' },
  { label: 'Narrativo / non databile', statuses: ['narrative', 'undatable'], description: 'tratteggio fine' },
];
function finite(v: unknown): v is number { return typeof v === 'number' && Number.isFinite(v); }
export function historicalMapLayerForType(type: string): MapLayer { if (type === 'city' || type === 'region') return 'places'; if (type === 'empire' || type === 'people' || type === 'person') return 'powers'; if (type === 'event') return 'events'; return 'texts'; }
function statusStroke(status?: MapEpistemicStatus) { if (!status || status === 'attested') return undefined; if (status === 'probable') return '8 2'; if (status === 'debated') return '6 4'; if (status === 'memory' || status === 'comparandum') return '3 4'; return '2 3'; }
function statusOpacity(status?: MapEpistemicStatus) { if (!status || status === 'attested') return 1; if (status === 'probable') return .92; if (status === 'debated') return .84; if (status === 'memory' || status === 'comparandum') return .76; return .7; }
function clampZoom(v: number) { return Math.max(MIN_ZOOM, Math.min(MAX_ZOOM, v)); }
function clampCamera(camera: Camera): Camera { const z = clampZoom(camera.zoom); if (z <= 1.0001) return { zoom: 1, x: 0, y: 0 }; const margin = 80; const minX = W - W * z - margin, maxX = margin; const minY = H - H * z - margin, maxY = margin; return { zoom: z, x: Math.max(minX, Math.min(maxX, camera.x)), y: Math.max(minY, Math.min(maxY, camera.y)) }; }
function nextSelection<T extends string>(current: T[], values: T[]) { const all = values.every((v) => current.includes(v)); return all ? current.filter((v) => !values.includes(v)) : Array.from(new Set([...current, ...values])); }
function spreadCoincident(points: Projected[]): DisplayPoint[] { const groups = new Map<string, Projected[]>(); points.forEach((p) => { const k = `${p.lat.toFixed(3)}:${p.lng.toFixed(3)}`; groups.set(k, [...(groups.get(k) ?? []), p]); }); return [...groups.values()].flatMap((g) => g.length === 1 ? [{ ...g[0], dx: 0, dy: 0, groupSize: 1 }] : g.map((p, i) => { const r = g.length <= 3 ? 14 : g.length <= 6 ? 20 : 26; const a = -Math.PI / 2 + Math.PI * 2 * i / g.length; return { ...p, dx: Math.cos(a) * r, dy: Math.sin(a) * r, groupSize: g.length }; })); }
function hexPoints(x: number, y: number, r: number) { return Array.from({ length: 6 }, (_, i) => { const a = Math.PI / 6 + i * Math.PI / 3; return `${x + Math.cos(a) * r},${y + Math.sin(a) * r}`; }).join(' '); }
function markerPriority(p: HistoricalMapPoint, selectedId?: string) { if (p.id === selectedId || p.selected) return 1000; if (p.type === 'city') return 800; if (p.type === 'region') return 720; if (p.type === 'empire') return 650; if (p.type === 'people') return 560; if (p.type === 'event') return 420; return 260; }

export default function HistoricalMapV2({ points, areas = [], selectedId, onSelect, preset, heightClassName = 'h-[430px] md:h-[520px]', headerRight, footer, contextTitle, contextSummary, visibleLayers, onVisibleLayersChange, visibleStatuses, onVisibleStatusesChange }: Props) {
  const [localLayers, setLocalLayers] = useState<MapLayer[]>(ALL_LAYERS);
  const [localStatuses, setLocalStatuses] = useState<MapEpistemicStatus[]>(ALL_STATUSES);
  const [camera, setCamera] = useState<Camera>({ zoom: 1, x: 0, y: 0 });
  const [dragging, setDragging] = useState(false);
  const [guideOpen, setGuideOpen] = useState(false);
  const [filtersOpen, setFiltersOpen] = useState(false);
  const svgRef = useRef<SVGSVGElement>(null);
  const pointersRef = useRef(new Map<number, { x: number; y: number }>());
  const gestureRef = useRef<{ mode: 'pan' | 'pinch'; x?: number; y?: number; camera?: Camera; distance?: number; center?: { x: number; y: number }; startCamera?: Camera } | null>(null);
  const layers = visibleLayers ?? localLayers, statuses = visibleStatuses ?? localStatuses;
  const setLayers = onVisibleLayersChange ?? setLocalLayers, setStatuses = onVisibleStatusesChange ?? setLocalStatuses;
  const cleanPoints = points.filter((p) => finite(p.lat) && finite(p.lng));
  const presetId = preset ?? inferHistoricalMapPreset(cleanPoints), mapPreset = historicalMapPresets[presetId];
  const { minLat, maxLat, minLng, maxLng } = mapPreset.bounds;
  const project = (lng: number, lat: number) => ({ x: (lng - minLng) / (maxLng - minLng) * W, y: (maxLat - lat) / (maxLat - minLat) * H });
  const polygon = (coords: number[][]) => coords.filter((c) => c.length >= 2 && finite(c[0]) && finite(c[1])).map(([lng, lat]) => { const p = project(lng, lat); return `${p.x},${p.y}`; }).join(' ');
  const filtered = cleanPoints.filter((p) => layers.includes(historicalMapLayerForType(p.type)) && statuses.includes(p.epistemicStatus ?? 'attested'));
  const projected: Projected[] = filtered.filter((p) => p.lng >= minLng && p.lng <= maxLng && p.lat >= minLat && p.lat <= maxLat).map((p) => ({ ...p, ...project(p.lng, p.lat) }));
  const hiddenOutsidePreset = filtered.length - projected.length;
  const visibleAreas = layers.includes('powers') ? areas.filter((a) => { const owner = cleanPoints.find((p) => p.id === a.entityId); return !owner || statuses.includes(owner.epistemicStatus ?? 'attested'); }) : [];

  const areaBounds = (coords: number[][]) => { const pts = coords.filter((c) => c.length >= 2 && finite(c[0]) && finite(c[1])).map(([lng, lat]) => project(lng, lat)); if (!pts.length) return null; return { minX: Math.min(...pts.map((p) => p.x)), maxX: Math.max(...pts.map((p) => p.x)), minY: Math.min(...pts.map((p) => p.y)), maxY: Math.max(...pts.map((p) => p.y)) }; };
  useEffect(() => {
    if (!selectedId) return;
    const point = projected.find((p) => p.id === selectedId);
    if (point) { const zoom = Math.max(camera.zoom, 1.75); setCamera(clampCamera({ zoom, x: W / 2 - point.x * zoom, y: H / 2 - point.y * zoom })); return; }
    const area = areas.find((a) => a.entityId === selectedId); const b = area ? areaBounds(area.coordinates) : null; if (!b) return;
    const bw = Math.max(80, b.maxX - b.minX), bh = Math.max(60, b.maxY - b.minY); const zoom = clampZoom(Math.min(W * .72 / bw, H * .72 / bh, 3)); const cx = (b.minX + b.maxX) / 2, cy = (b.minY + b.maxY) / 2; setCamera(clampCamera({ zoom, x: W / 2 - cx * zoom, y: H / 2 - cy * zoom }));
  }, [selectedId, presetId]);

  const zoomAt = (factor: number, cx = W / 2, cy = H / 2) => setCamera((cur) => { const zoom = clampZoom(cur.zoom * factor); const wx = (cx - cur.x) / cur.zoom, wy = (cy - cur.y) / cur.zoom; return clampCamera({ zoom, x: cx - wx * zoom, y: cy - wy * zoom }); });
  const resetCamera = () => setCamera({ zoom: 1, x: 0, y: 0 });
  useEffect(() => { const node = svgRef.current; if (!node) return; const wheel = (e: WheelEvent) => { e.preventDefault(); const r = node.getBoundingClientRect(); const cx = (e.clientX - r.left) * W / r.width, cy = (e.clientY - r.top) * H / r.height; zoomAt(e.deltaY < 0 ? 1.16 : .86, cx, cy); }; node.addEventListener('wheel', wheel, { passive: false }); return () => node.removeEventListener('wheel', wheel); }, []);

  const pointerPos = (e: ReactPointerEvent<SVGSVGElement>) => { const r = svgRef.current!.getBoundingClientRect(); return { x: (e.clientX - r.left) * W / r.width, y: (e.clientY - r.top) * H / r.height }; };
  const handlePointerDown = (e: ReactPointerEvent<SVGSVGElement>) => { if (e.pointerType === 'mouse' && e.button !== 0) return; e.currentTarget.setPointerCapture(e.pointerId); const p = pointerPos(e); pointersRef.current.set(e.pointerId, p); if (pointersRef.current.size === 1) gestureRef.current = { mode: 'pan', x: p.x, y: p.y, camera: { ...camera } }; else if (pointersRef.current.size === 2) { const [a, b] = [...pointersRef.current.values()]; gestureRef.current = { mode: 'pinch', distance: Math.hypot(b.x - a.x, b.y - a.y), center: { x: (a.x + b.x) / 2, y: (a.y + b.y) / 2 }, startCamera: { ...camera } }; } setDragging(true); };
  const handlePointerMove = (e: ReactPointerEvent<SVGSVGElement>) => { if (!pointersRef.current.has(e.pointerId)) return; pointersRef.current.set(e.pointerId, pointerPos(e)); const g = gestureRef.current; if (!g) return; if (pointersRef.current.size >= 2) { const [a, b] = [...pointersRef.current.values()]; const distance = Math.hypot(b.x - a.x, b.y - a.y), center = { x: (a.x + b.x) / 2, y: (a.y + b.y) / 2 }; if (g.mode !== 'pinch' || !g.distance || !g.center || !g.startCamera) { gestureRef.current = { mode: 'pinch', distance, center, startCamera: { ...camera } }; return; } const zoom = clampZoom(g.startCamera.zoom * distance / g.distance); const wx = (g.center.x - g.startCamera.x) / g.startCamera.zoom, wy = (g.center.y - g.startCamera.y) / g.startCamera.zoom; setCamera(clampCamera({ zoom, x: center.x - wx * zoom, y: center.y - wy * zoom })); return; } if (g.mode === 'pan' && g.camera && finite(g.x) && finite(g.y)) { const p = [...pointersRef.current.values()][0]; setCamera(clampCamera({ ...g.camera, x: g.camera.x + p.x - g.x, y: g.camera.y + p.y - g.y })); } };
  const handlePointerUp = (e: ReactPointerEvent<SVGSVGElement>) => { pointersRef.current.delete(e.pointerId); try { e.currentTarget.releasePointerCapture(e.pointerId); } catch {} if (pointersRef.current.size === 1) { const p = [...pointersRef.current.values()][0]; gestureRef.current = { mode: 'pan', x: p.x, y: p.y, camera: { ...camera } }; } else if (!pointersRef.current.size) { gestureRef.current = null; setDragging(false); } };

  const clusters = useMemo<Cluster[]>(() => {
    if (camera.zoom >= 1.55) return [];
    const grid = 64; const groups = new Map<string, Projected[]>();
    projected.forEach((p) => { if (p.id === selectedId) return; const sx = p.x * camera.zoom + camera.x, sy = p.y * camera.zoom + camera.y; const key = `${Math.floor(sx / grid)}:${Math.floor(sy / grid)}`; groups.set(key, [...(groups.get(key) ?? []), p]); });
    return [...groups.entries()].filter(([, pts]) => pts.length > 1).map(([key, pts]) => ({ key, points: pts, x: pts.reduce((s, p) => s + p.x, 0) / pts.length, y: pts.reduce((s, p) => s + p.y, 0) / pts.length }));
  }, [projected, camera.zoom, camera.x, camera.y, selectedId]);
  const clusteredIds = new Set(clusters.flatMap((c) => c.points.map((p) => p.id)));
  const displayPoints = spreadCoincident(projected.filter((p) => !clusteredIds.has(p.id)));

  const labelIds = useMemo(() => {
    const candidates = displayPoints.filter((p) => p.id === selectedId || p.selected || (p.active !== false && (camera.zoom >= 2.5 || (camera.zoom >= 1.75 && ['city', 'region', 'empire', 'event'].includes(p.type)) || (camera.zoom < 1.75 && ['city', 'region', 'empire'].includes(p.type))))).sort((a, b) => markerPriority(b, selectedId) - markerPriority(a, selectedId));
    const boxes: Array<{ l: number; r: number; t: number; b: number }> = []; const accepted = new Set<string>();
    for (const p of candidates) { const x = (p.x + p.dx) * camera.zoom + camera.x, y = (p.y + p.dy) * camera.zoom + camera.y; const fs = (p.id === selectedId ? 15 : 12) * camera.zoom; const width = Math.min(300, Math.max(45, p.label.length * fs * .52)); const box = { l: x + 10 * camera.zoom, r: x + 10 * camera.zoom + width, t: y - 30 * camera.zoom, b: y - 7 * camera.zoom }; const collision = boxes.some((q) => !(box.r + 6 < q.l || box.l - 6 > q.r || box.b + 4 < q.t || box.t - 4 > q.b)); if (!collision || p.id === selectedId) { accepted.add(p.id); boxes.push(box); } }
    return accepted;
  }, [displayPoints, camera, selectedId]);

  const renderMarker = (p: DisplayPoint) => { const x = p.x + p.dx, y = p.y + p.dy, selected = p.id === selectedId || p.selected, layer = historicalMapLayerForType(p.type), color = selected ? '#a06c35' : layerMeta[layer].color, r = selected ? 11 : layer === 'powers' ? 10 : layer === 'places' ? 7 : 8, dash = statusStroke(p.epistemicStatus), opacity = (p.active === false && !selected ? .28 : 1) * statusOpacity(p.epistemicStatus), label = labelIds.has(p.id); return <g key={p.id} opacity={opacity} role={onSelect ? 'button' : undefined} tabIndex={onSelect ? 0 : undefined} className={onSelect ? 'cursor-pointer focus:outline-none focus-visible:[filter:drop-shadow(0_0_5px_#a06c35)]' : ''} onPointerDown={(e) => e.stopPropagation()} onClick={() => onSelect?.(p.id)} onKeyDown={(e) => { if (onSelect && (e.key === 'Enter' || e.key === ' ')) { e.preventDefault(); onSelect(p.id); } }} aria-label={p.label}>{p.groupSize > 1 && <line x1={p.x} y1={p.y} x2={x} y2={y} stroke="#7f6d59" strokeWidth="1" opacity=".3" />}{selected && <circle cx={x} cy={y} r="19" fill="none" stroke="#a06c35" strokeWidth="3" opacity=".42" />}{layer === 'places' && p.type === 'region' ? <><circle cx={x} cy={y} r={selected ? 11 : 9} fill="#f7f1e7" fillOpacity=".82" stroke={color} strokeWidth={selected ? 3 : 2} strokeDasharray={dash ?? '3 2'} /><circle cx={x} cy={y} r="2.8" fill={color} /></> : null}{layer === 'places' && p.type !== 'region' ? <circle cx={x} cy={y} r={r} fill={color} stroke="#f8f1e5" strokeWidth={selected ? 3 : 2} strokeDasharray={dash} /> : null}{layer === 'powers' ? <polygon points={hexPoints(x, y, r)} fill={color} stroke="#f8f1e5" strokeWidth={selected ? 3 : 2} strokeDasharray={dash} /> : null}{layer === 'events' ? <rect x={x-r*.72} y={y-r*.72} width={r*1.44} height={r*1.44} fill={color} stroke="#f8f1e5" strokeWidth={selected ? 3 : 2} strokeDasharray={dash} transform={`rotate(45 ${x} ${y})`} /> : null}{layer === 'texts' ? <><rect x={x-r} y={y-r} width={r*2} height={r*2} rx="2" fill="#f6eddf" stroke={color} strokeWidth={selected ? 3 : 2} strokeDasharray={dash} /><circle cx={x} cy={y} r="3" fill={color} /></> : null}{label && <text x={x+13} y={y-12} fill={color} fontFamily="Georgia, serif" fontSize={selected ? 15 : 12} fontWeight={selected ? 700 : 600} stroke="#f1e8d8" strokeWidth="4" paintOrder="stroke" strokeLinejoin="round">{p.label}</text>}<title>{layerMeta[layer].label}: {p.label}</title></g>; };

  return <div className="overflow-hidden rounded-2xl border border-papyrus-line bg-paper-card shadow-sm">
    <div className="flex flex-wrap items-center justify-between gap-2 border-b border-papyrus-line bg-[#132630] px-4 py-2 text-[#e8dfd2]"><div><span className="font-mono text-[9px] uppercase tracking-[.17em] text-[#c9bca9]">Carta storica · {mapPreset.label}</span><span className="ml-3 hidden text-[10px] text-[#9e9487] md:inline">Historical Map UX 1.0</span></div><div className="flex items-center gap-3 text-[11px] text-[#c9bca9]"><span>{headerRight}</span><span className="font-mono">{Math.round(camera.zoom*100)}%</span></div></div>
    <div className="border-b border-papyrus-line bg-[#f3ecdf] px-3 py-2.5 md:px-4">
      <button type="button" onClick={() => setFiltersOpen((v) => !v)} className="mb-2 inline-flex rounded-full border border-[#cdbfae] px-3 py-1.5 text-[10px] font-semibold text-[#675947] md:hidden" aria-expanded={filtersOpen}>Livelli e statuto {filtersOpen ? '▴' : '▾'}</button>
      <div className={`${filtersOpen ? 'flex' : 'hidden'} flex-wrap gap-2 md:flex md:items-center md:justify-between`}><div className="flex flex-wrap items-center gap-1.5"><span className="mr-1 font-mono text-[9px] uppercase tracking-[.15em] text-[#756957]">Livelli</span>{(Object.keys(layerMeta) as MapLayer[]).map((layer) => { const active = layers.includes(layer), meta = layerMeta[layer]; return <button key={layer} type="button" aria-pressed={active} onClick={() => setLayers(nextSelection(layers,[layer]))} className={`rounded-full border px-2.5 py-1.5 text-[9px] font-semibold ${active ? 'border-[#9b6a38] bg-[#9b6a38] text-white' : 'border-[#cdbfae] text-[#756957]'}`}><span className="mr-1">{meta.glyph}</span>{meta.label}</button>; })}</div><div className="flex flex-wrap items-center gap-1.5"><span className="mr-1 font-mono text-[9px] uppercase tracking-[.15em] text-[#756957]">Statuto</span>{statusGroups.map((g) => { const active = g.statuses.every((s) => statuses.includes(s)); return <button key={g.label} type="button" aria-pressed={active} title={g.description} onClick={() => setStatuses(nextSelection(statuses,g.statuses))} className={`rounded-full border px-2 py-1.5 text-[9px] ${active ? 'border-[#756957] bg-white/70 text-[#4e4438]' : 'border-[#d6cab9] text-[#9a8f80]'}`}>{g.label}</button>; })}</div></div>
    </div>
    <div className={`relative overflow-hidden bg-[#dfe7e8] ${heightClassName}`}>
      <div className="absolute right-3 top-3 z-10 flex flex-col overflow-hidden rounded-lg border border-[#b7aa97] bg-[#f8f2e7]/95 shadow-sm"><button type="button" onClick={() => zoomAt(1.28)} className="h-10 w-10 border-b border-[#d8cbbb] text-lg font-bold" aria-label="Ingrandisci">+</button><button type="button" onClick={() => zoomAt(.78)} className="h-10 w-10 border-b border-[#d8cbbb] text-lg font-bold" aria-label="Riduci">−</button><button type="button" onClick={resetCamera} className="h-10 w-10 text-[15px]" aria-label="Mostra intera carta">⌂</button></div>
      <div className="absolute bottom-3 left-3 z-10 hidden rounded-md border border-[#b7aa97] bg-[#f8f2e7]/90 px-2 py-1 text-[9px] text-[#756957] shadow-sm sm:block">Trascina · rotella o +/− · pinch su touch</div>
      <svg ref={svgRef} viewBox={`0 0 ${W} ${H}`} className={`block h-full w-full touch-none select-none ${dragging?'cursor-grabbing':'cursor-grab'}`} role="img" aria-label={`Mappa storica interattiva: ${mapPreset.label}`} onPointerDown={handlePointerDown} onPointerMove={handlePointerMove} onPointerUp={handlePointerUp} onPointerCancel={handlePointerUp}>
        <g transform={`translate(${camera.x} ${camera.y}) scale(${camera.zoom})`}><image href={baseAssets[presetId]} x="0" y="0" width={W} height={H} preserveAspectRatio="none" />{mapPreset.waterLabels.map((l) => { const p=project(l.lng,l.lat); return <text key={l.label} x={p.x} y={p.y} textAnchor="middle" fill="#647d84" fontFamily="Georgia, serif" fontStyle="italic" fontSize="18" letterSpacing="5" opacity={camera.zoom>2.6?.28:.66}>{l.label}</text>; })}{mapPreset.regionLabels.map((l) => { const p=project(l.lng,l.lat); return <text key={l.label} x={p.x} y={p.y} textAnchor="middle" fill="#756957" fontFamily="Georgia, serif" fontSize={l.size==='lg'?18:l.size==='md'?15:12} fontWeight="600" letterSpacing="4" opacity={camera.zoom>2.6?.25:.62}>{l.label}</text>; })}{visibleAreas.map((a) => { const selected=a.entityId===selectedId, owner=cleanPoints.find((p)=>p.id===a.entityId); return <polygon key={a.id} points={polygon(a.coordinates)} fill={selected?'rgba(160,108,53,.24)':'rgba(155,106,56,.13)'} stroke={selected?'#a06c35':'rgba(128,84,43,.76)'} strokeWidth={selected?3:2} strokeDasharray={statusStroke(owner?.epistemicStatus)??'8 7'} className={onSelect?'cursor-pointer':''} onPointerDown={(e)=>e.stopPropagation()} onClick={()=>onSelect?.(a.entityId)}><title>{a.label}</title></polygon>; })}{clusters.map((c) => <g key={c.key} className="cursor-zoom-in" onPointerDown={(e)=>e.stopPropagation()} onClick={() => { const zoom=Math.max(2,camera.zoom*1.7); setCamera(clampCamera({zoom,x:W/2-c.x*zoom,y:H/2-c.y*zoom})); }}><circle cx={c.x} cy={c.y} r="16" fill="#132630" stroke="#f8f1e5" strokeWidth="3"/><text x={c.x} y={c.y+4} textAnchor="middle" fill="#f8f1e5" fontFamily="system-ui" fontSize="11" fontWeight="700">{c.points.length}</text><title>{c.points.length} elementi vicini · clicca per espandere</title></g>)}{displayPoints.map(renderMarker)}</g>
      </svg>
    </div>
    <div className="border-t border-papyrus-line bg-[#132630] px-4 py-2 text-[10px] leading-5 text-[#b9aa94]">{footer ?? 'Base geografica comune di Biblia Fontes.'}{hiddenOutsidePreset>0&&<span className="ml-2">{hiddenOutsidePreset} elementi fuori dalla finestra corrente.</span>}</div>
    <div className="border-t border-papyrus-line bg-[#f7f1e7] p-4 md:p-5"><div className="flex flex-wrap items-start justify-between gap-3"><div><p className="font-mono text-[9px] uppercase tracking-[.17em] text-[#9b6a38]">Come leggere questa carta</p><h4 className="mt-1 font-serif text-lg font-bold text-[#2f2924]">{contextTitle?`La geografia di ${contextTitle}`:'Che cosa stai vedendo'}</h4></div><button type="button" onClick={()=>setGuideOpen((v)=>!v)} className="rounded-full border border-[#cdbfae] px-3 py-1.5 text-[10px] font-semibold text-[#675947]">{guideOpen?'Riduci guida':'Apri guida completa'}</button></div><p className="mt-2 max-w-4xl text-xs leading-5 text-[#756957]">{contextSummary??`La carta mette in relazione la geografia di ${mapPreset.label} con luoghi, poteri, eventi e processi testuali pertinenti alla scena selezionata.`}</p><div className="mt-3 flex flex-wrap gap-x-4 gap-y-2 rounded-lg border border-[#d8cbbb] bg-white/45 px-3 py-2 text-[10px] text-[#5f5548]"><span><strong>●</strong> città</span><span><strong>◉</strong> regione</span><span><strong>⬡</strong> potere</span><span><strong>◆</strong> evento</span><span><strong>▣</strong> testo/tradizione</span><span><strong>numero</strong> cluster da espandere</span><span><strong>area</strong> territorio ricostruito</span><span><strong>○</strong> selezione</span></div>{guideOpen&&<div className="mt-3 grid gap-3 lg:grid-cols-2"><div className="rounded-lg border border-[#d8cbbb] bg-white/35 p-3"><strong className="text-[10px] uppercase tracking-wide text-[#756957]">Natura dell'entità</strong><p className="mt-2 text-[10px] leading-5 text-[#756957]">La forma del simbolo distingue luogo, potere, evento e processo testuale. I cluster numerati raccolgono elementi troppo vicini alla scala corrente e si aprono aumentando lo zoom.</p></div><div className="rounded-lg border border-[#d8cbbb] bg-white/35 p-3"><strong className="text-[10px] uppercase tracking-wide text-[#756957]">Statuto epistemico</strong><p className="mt-2 text-[10px] leading-5 text-[#756957]">Il bordo comunica lo statuto: pieno per attestato, progressivamente tratteggiato per probabile, discusso, memoria/comparandum o narrativo.</p></div><p className="lg:col-span-2 rounded-lg border border-[#d8cbbb] bg-white/45 px-3 py-2 text-xs leading-5 text-[#5f5548]"><strong>Regola di lettura:</strong> la posizione indica una coordinata o un contesto geografico. Le etichette sono mostrate per priorità e senza sovrapporsi; aumentano con lo zoom e la selezione ha sempre precedenza.</p></div>}</div>
  </div>;
}
